### ISSUE TITLE
Software Sources Not Working In Wayland

### ISSUE THREAD

**Issue by RTinIB** [linuxmint/mint21.3-beta#22] opened 2023-12-13 21:00 UTC
Software Sources is not working from the menu in Wayland. mintsources works if invoked from the terminal. Software Sources works from the menu in X11.

**Comment by rcalixte** [comment] 2023-12-13 21:44
This is a duplicate of linuxmint/wayland#22.

**Comment by RTinIB** [comment] 2023-12-13 22:12
Sorry, I did not see the github wayland link in the new features page.

**Closed as completed** 2023-12-14 10:19 UTC
