### ISSUE TITLE
Installer freezes when trying to create BTRFS Partition

### ISSUE THREAD

**Issue by ghost** [linuxmint/mint21.3-beta#10] opened 2023-12-10 18:12 UTC
System information:
Mint 21.3 Cinnamon Beta virtual machine
`inxi
CPU: 8-core AMD Ryzen 7 5700GE with Radeon Graphics (-MT MCP-)
speed: 3194 MHz Kernel: 5.15.0-89-generic x86_64 Up: 44m
Mem: 1594.0/3908.6 MiB (40.8%) Storage: 0/64 GiB  Procs: 320
Shell: Bash inxi: 3.3.13
`

Host information:
Mint 21.2 Cinnamon
`inxi
CPU: 8-core AMD Ryzen 7 5700GE with Radeon Graphics (-MT MCP-)
speed/min/max: 1415/1400/4659 MHz Kernel: 6.2.0-37-generic x86_64 Up: 3h 36m
Mem: 9115.5/15281.0 MiB (59.7%) Storage: 953.87 GiB (67.6% used) Procs: 481
Shell: Bash inxi: 3.3.13
`
Gnome Boxes 45.0-fe0ca772 Flatpak

Steps to reproduce:
1) Launch Mint in a box.
2)Click "Install Linux Mint."
3)Accept default options until it is time to create file system partitions.
4)Click "something else."
5)Attempt to create a BTRFS partition instead of Ext4.

Expected results: The installer should allow you to continue through the installation process.
Actual result: The installer generates a pop-up window with the header 

> ubi-partman crashed

and the message

> ubi-partman failed with exit code 141. Further information may be found in /var/log/syslog. Do you want to try running this step again before continuing? If you do not, your installation may fail entirely or may be broken.

The popup window contains an "x" in the top-right corner, as well as three additional buttons: "quit," "continue anyway," and "try again."  However, none of these buttons work.   Clicking on them does nothing, and I can't find any way to close this popup winow.  The installer's window is also completely frozen and cannot be closed.

Nemo still works, so I can still navigte to /var/log/syslog.  [Here's a pastebin](https://pastebin.com/0VBzmHXe) of that file.

**Comment by anaximeno** [comment] 2023-12-11 00:42
I am not sure if the problem is specifically with BTRFS, because I was capable of making a complete installation in my system. Do you have more than one disk in your system?

**Comment by anaximeno** [comment] 2023-12-11 00:42
I am not sure if the problem is specifically with BTRFS, because I was capable of making a complete installation in my system.

**Comment by ghost** [comment] 2023-12-11 15:54
Nope, I only have one disk (on both the host and guest system).

**Comment by anaximeno** [comment] 2023-12-12 02:49
Can you share a screenshot of the partitioning section after defining the structure and before clicking to contribute?

Edit: actually you are not even being able to define the structure of the partitioning using btrfs, right?

**Comment by Elliot4444** [comment] 2023-12-13 10:52
Maybe it is Gnome Boxes. I tried the same in Virtual Box with nearly the same configuration and it works flawlessly.

**Comment by ghost** [comment] 2023-12-23 23:01
> Can you share a screenshot of the partitioning section after defining the structure and before clicking to contribute?
> 
> Edit: actually you are not even being able to define the structure of the partitioning using btrfs, right?

Your edit is correct.

**Comment by clefebvre** [comment] 2024-01-04 13:04
Based on @Elliot4444 and @anaximeno experience this seems to only affect this particular scenario (Gnome Boxes + BTRFS). All relevant components are also upstream from us (ubi-partman, grub, gnome-boxes). Going forward we might not even continue using ubiquity..

This won't lead to a fix here so I'll close the issue.

**Closed as completed by clefebvre** 2024-01-04 13:04 UTC
